{% set version = "2019.12.3" %}

package:
  name: imagecodecs-lite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imagecodecs-lite/imagecodecs-lite-{{ version }}.tar.gz
  sha256: 95d18aa13ceb1b18a6109433b42d054e13b9a295cba96c08ab719f864f589d68

build:
  number: 9
  script:
    - "{{ PYTHON }} -m  cython imagecodecs/_imagecodecs_lite.pyx"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - msinttypes  # [win]
    - cython
  run:
    - python

test:
  imports:
    - imagecodecs_lite

about:
  home: https://www.lfd.uci.edu/~gohlke
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Subset of image transformation, compression, and decompression codecs"

extra:
  recipe-maintainers:
    - ocefpaf
